### ISSUE TITLE
Suggested to hide Followers

### ISSUE THREAD

**Issue by verma-kunal** [EmanuelGF/EmanuelGF#1]
As the number of followers are already mentioned under your name in GitHub, I would suggest to not mention that in your **Readme profile**

Followers visible on GitHub:
![Screenshot 2021-05-23 at 9 45 11 PM](https://user-images.githubusercontent.com/72245772/119268350-28816780-bc10-11eb-9137-8ec0afc62112.png)

Your Profile:
![Screenshot 2021-05-23 at 9 45 32 PM](https://user-images.githubusercontent.com/72245772/119268359-346d2980-bc10-11eb-8d48-35ca5f6677cd.png)

**Comment by EmanuelGF** [comment]
@verma-kunal I had the same thought but still went ahead  because I liked how the badges looked 😁. You are right, thank you to point that out to me.  👍

**Comment by EmanuelGF** [comment]
@verma-kunal I had that thought as I was updating the profile, but still went on because the badges look cool 😆. But you are totally right. Thank you for pointing that out 👍

**Comment by EmanuelGF** [comment]
If you can tell me your github email I can co-author you on the commit ;)

**Comment by verma-kunal** [comment]
> If you can tell me your github email I can co-author you on the commit ;)

Oh! Thank you for that !! Its `vkunal321@gmail.com`

**Comment by verma-kunal** [comment]
> @verma-kunal I had the same thought but still went ahead because I liked how the badges looked 😁. You are right, thank you to point that out to me. 👍

No problem !! Happy to help 😃
